version: '3'
# 启动的服务
services:
  craft-mongo:
    image: mongo:4.4.6
    container_name: craft-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db' # 持久化地址
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/' # 
    ports:
      - 27016:27017
    env_file: # 环境变量文件
      - .env
  craft-redis:
    image: redis:6
    container_name: craft-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6377:6379
    env_file:
      - .env
  sharecraft-backend:
    image: registry.cn-hangzhou.aliyuncs.com/supercll/craft:{{tag}}
    container_name: sharecraft-backend
    build:
      context: .
      dockerfile: Dockerfile-py
    depends_on: # 依赖的服务
      - craft-mongo
      - craft-redis
    ports:
      - 7002:7001
    env_file:
      - .env
