version: '3'
services:
  craft-mongo:
    image: mongo
    container_name: craft-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27018:27017
    env_file:
      - .env
  craft-redis:
    image: redis:6
    container_name: craft-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6378:6379
    env_file:
      - .env
  craft-backend:
    depends_on:
      - craft-mongo
      - craft-redis
    build:
      context: . # 当前目录
      dockerfile: Dockerfile
    image: craft-backend
    container_name: craft-backend
    ports:
      - 7001:7001
    env_file:
      - .env
