version: '3'
services:
  craft-mongo:
    image: mongo
    container_name: craft-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
    ports:
      - 27017:27017
  sharecraft-backend:
    depends_on:
      - craft-mongo
    build:
      context: . # 当前目录
      dockerfile: Dockerfile
    image: sharecraft-backend
    container_name: sharecraft-backend
    ports:
      - 7001:7001
